// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghtqdgkfbfdlnowrowpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodHFkZ2tmYmZkbG5vd3Jvd3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDQ1OTAsImV4cCI6MjA2MTEyMDU5MH0.aK1kIjz-AoTdPZqHwzwKxY39o9G8CBuBMly7DEwV2DY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);